### PR TITLE
enabled custom filters in metric-aggr

### PR DESCRIPTION
**Pull request by harshit-splunk**
Fixing https://github.com/splunk/splunk-connect-for-kubernetes/issues/621

### CODE REVIEW

**Review by chaitanyaphalak — DISMISSED** [review]

**Comment by harshit-splunk** [comment]
I have rebased with develop.

**Review by rockb1017 — CHANGES_REQUESTED** [review]
let's add `aggrCustomFilters:` to values.yaml so that user can specify a different custom filter.

**Comment by harshit-splunk** [comment]
> let's add `aggrCustomFilters:` to values.yaml so that user can specify a different custom filter.
There is already custom filter example in values.yaml file (https://github.com/splunk/splunk-connect-for-kubernetes/blob/d8a62ec04d13499ed675dc521672e6b827b6bf53/helm-chart/splunk-connect-for-kubernetes/values.yaml#L489-L501).
It is same for all SCK plug-in. Same example would apply for this plugin as well.
What are your thoughts?

**Comment by chaitanyaphalak** [comment]
I think @rockb1017 is right on this one, we need to differentiate between filters for metrics and metrics-agg

**Comment by harshit-splunk** [comment]
Hey @rockb1017, added `customFiltersAggr` config

**Review by rockb1017 — APPROVED** [review]

**Pull request merged**
