### PR TITLE
Fix concat

### PR DESCRIPTION
**Pull request by matthewmodestino**
## Proposed changes

This is an attempt to fix concat "recursive deadlock"  error https://github.com/splunk/splunk-connect-for-kubernetes/issues/358

In summary the changes are:
- remove default CONCAT filters from values.yaml in umbrella and logging chart, future PR could add them back as optional or commented out as examples. 
- remove audit log as a default custom log source. It shoudn't be watched by default due to volume/impact it can have, should be added back as optional
- update container, custom file & journald source to emit to a new label called CONCAT
- Add new CONCAT label to output.conf
- Move concat filters for container, custom file and journal out of SPLUNK label and into CONCAT label
- add relabel filter at bottom of CONCAT label to ensure all logs end up emitted to SPLUNK whether they are concat timeout, or don't match any concat filters. 

I will follow up this change with one that will also expose the CONCAT separator option (and any other needed features) to ensure each concat filter can be customized to render the log as needed. For example some need a "\n" some need ""

PR should also be made to guard the "customFilters" option in values.yaml to NOT use CONCAT, as it renders at the bottom of the SPLUNK label and would trigger this issue again.  We should probably add a second option for customConcatFilters, or something to ensure they render in the CONCAT label. 

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [X ] I have read the [CONTRIBUTING](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CONTRIBUTING.md) doc
- [ X] I have read the [CLA](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CLA.md)
- [ X] I have added necessary documentation (if appropriate)
- [ X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by matthewmodestino** [comment]
Looks like the PR added changes to the notes which i didnt actually do, i guess they just got picked up in bringing my branch off of master. the hey changes are just the 2x values.yaml and logging configmap edits.

**Comment by matthewmodestino** [comment]
https://github.com/splunk/splunk-connect-for-kubernetes/pull/352

This PR implemements some of what I was alluding to here:

~ PR should also be made to guard the "customFilters" option in values.yaml to NOT use CONCAT, as it renders at the bottom of the SPLUNK label and would trigger this issue again. We should probably add a second option for customConcatFilters, or something to ensure they render in the CONCAT label.

**Comment by rockb1017** [comment]
Thank you for contribution. 
it has to go through functional test pipeline, and only internal developers can trigger the pipeline. i have taken your changes in this PR https://github.com/splunk/splunk-connect-for-kubernetes/pull/369

**Comment by rockb1017** [comment]
Merged

**Comment by szymonpk** [comment]
@rockb1017 can we have a release with this fix?

**Comment by rockb1017** [comment]
it is being worked on. thank you.

**Pull request closed without merging**
