### PR TITLE
Support setting gzip_compression flag for log forwarder

### PR DESCRIPTION
**Pull request by toscott**
## Functionality depends on an upstream change
https://github.com/splunk/fluent-plugin-splunk-hec/pull/250

## Proposed changes

Support potential new flag for gzip compression from:
https://github.com/splunk/fluent-plugin-splunk-hec/pull/250

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CONTRIBUTING.md) doc
- [x] I have read the [CLA](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CLA.md)
- [x] I have added necessary documentation (if appropriate)

Hoping this PR might help with visibility on the upstream change.
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by harshit-splunk — CHANGES_REQUESTED** [review]
I think gzip_compression should defaults to false

**Comment by harshit-splunk** [comment]
Can you also fix lint test failures?

**Comment by toscott** [comment]
> I think gzip_compression should defaults to false

Fair. Will adjust

> Can you also fix lint test failures?

Yup. Will push in a bit.

**Comment by harshit-splunk** [comment]
I cannot merge it until splunk_hec plugin is released

**Review by harshit-splunk — APPROVED** [review]

**Pull request merged**
