### PR TITLE
Adding an optional clusterName value in order to have the ability to filter by a cluster_name field in splunk.

### PR DESCRIPTION
**Pull request by shaunhouseman**
Logs being collected into splunk will have a new field called "cluster_name".

### CODE REVIEW

**Comment by dbaldwin-splunk** [comment]
@dtregonning Can you review PR for 1.1?

**Comment by gp510** [comment]
@shaunhouseman - Thanks for this PR. We've moved it to the develop branch.

**Comment by p-id** [comment]
Any idea when support for additional field cluster-Id would make it to the next release 1.0.2

**Comment by dtregonning** [comment]
@p-id Release 1.1 will be out in the next day or two

**Comment by p-id** [comment]
Thanks for the quick revert @dtregonning would surely like to give this a try this week.

**Pull request merged**
