### PR TITLE
Support env variable for hec_host

### LINKED ISSUE #316: Can't use special character in hec_host
We have are deploying kubernetes in an existing infra where splunk connect is already part of the standard setup. Splunk Connect is the obvious choice to handle containers logs, however we would like to use the existing forwarder on the node to relay to the indexers. 

As the chart already exposes the host name as an environment variable, this only requires to set hec_host to #{ENV['NODE_NAME']}

**What happened**:
The containers go in a crashloop with the following error : 
```
[error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="hec_host (\#{ENV['NODE_NAME']}) and/or hec_port (8088) are invalid."
```
**What you expected to happen**:
That the pods would start, and send the logs to the HEC on the local forwarder

**How to reproduce it (as minimally and precisely as possible)**:
Set splunk.hec.host to  "#{ENV['NODE_NAME']}"  and deploy the chart

**Anything else we need to know?**:
This is fixed by quoting the value in each configMap.yaml template

**Environment**:
- Kubernetes version (use `kubectl version`):
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`):
- Splunk version: 
- Others:

### PR DESCRIPTION
**Pull request by fpicot**
## Proposed changes
Support passing env variable to hec_host parameter

Fixes #316 

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CONTRIBUTING.md) doc
- [x] I have read the [CLA](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CLA.md)
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by rockb1017** [comment]
does this commit alone support env var for hec_host?

**Comment by fpicot** [comment]
@rockb1017 Yes, with only this change to the release 1.3.0, I'm able to deploy and get the logs with the following values : 
```
global:
  splunk:
    hec:
      host: "#{ENV['NODE_NAME']}"
```

**Comment by fpicot** [comment]
Release 1.4.0 fixes the issue, this is not needed anymore.

**Comment by rockb1017** [comment]
Thank you!

**Pull request closed without merging**
