### PR TITLE
updated functional test for metric

### PR DESCRIPTION
**Pull request by harshit-splunk**

### CODE REVIEW

**Comment by harshit-splunk** [comment]
Already fixed in https://github.com/splunk/fluent-plugin-k8s-metrics-agg/pull/77/

- kube.node.cpu.reservation
- kube.node.cpu.utilization
- kube.node.memory.reservation
- kube.node.memory.utilization

Will be fixed in https://github.com/splunk/fluent-plugin-kubernetes-metrics/pull/108

- kube.pod.cpu.usage_rate
- kube.container.cpu.usage_rate

Need to look into this

- kube.namespace.cpu.usage

**Review by rockb1017 — CHANGES_REQUESTED** [review]
A lot is parameterized and nice, but it is less easy to see what it is testing. 

Could you share the logs when some test fails? 
I want to make sure that when it fails, it is clear and easy to find out what failed.

**Comment by rockb1017** [comment]
I have updated the image. https://github.com/splunk/splunk-connect-for-kubernetes/pull/706
now all tests should pass right? could you update it?

**Comment by harshit-splunk** [comment]
Moving this PR to different one as commit history is messy here.

**Pull request closed without merging**
