### PR TITLE
extensions/v1beta1 -> apps/v1

### PR DESCRIPTION
**Pull request by rhockenbury**
## Proposed changes

extensions/v1beta1 will be deprecated in 1.16. See release notes - https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#deprecations-and-removals

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CONTRIBUTING.md) doc
- [x] I have read the [CLA](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CLA.md)
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by chaitanyaphalak** [comment]
While you are at it I would recommend you to change the following deprecations to

1. https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-kubernetes-objects/templates/deployment.yaml#L1
2. https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/helm-chart/splunk-kubernetes-metrics/templates/deploymentMetricsAggregator.yaml#L1

**Comment by rhockenbury** [comment]
Updated.  Please review again.

**Comment by rhockenbury** [comment]
I'll need to update this.  Just realized today during testing that `apps/v1` requires an explicit selector field.

**Comment by rhockenbury** [comment]
Please review again.

**Pull request merged**
