### PR TITLE
Endline Reqexp (#459)

### PR DESCRIPTION
**Pull request by Kisalci90**
## Proposed changes

I raised this PR based on this issue, [#459 ](https://github.com/splunk/splunk-connect-for-kubernetes/issues/459)
I would like to add a new property endline to multiline log to support multiline_end_regexp in concat filter plugin.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CONTRIBUTING.md) doc
- [x] I have read the [CLA](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CLA.md)
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by rockb1017 — COMMENTED** [review]
Thank you, looks good. Would you be also interested in adding test case for it? we have opened the pipeline for all

**Comment by rockb1017** [comment]
would you also edit the values.yaml file for umbrella chart as well?

**Comment by Kisalci90** [comment]
> would you also edit the values.yaml file for umbrella chart as well?

I edited the umbrella chart also.

**Comment by Kisalci90** [comment]
> Thank you, looks good. Would you be also interested in adding test case for it? we have opened the pipeline for all

I would be happy to add a test case. I saw you are using rock1017/log-generator image to generate the logs. If we want to test it we need to generate logs that are bigger than 16k then the Docker will split up the logs entry. How can I contribute to this logs generator?

**Comment by sbkg0002** [comment]
Is this one to be merged?

**Review by rockb1017 — APPROVED** [review]

**Pull request merged**
