### PR TITLE
Makes monitoring agent is optional

### PR DESCRIPTION
**Pull request by retraut**
## Proposed changes
Makes monitoring_agent in fluentd config is optional
## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CONTRIBUTING.md) doc
- [x] I have read the [CLA](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CLA.md)
- [ ] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by matthewmodestino** [comment]
🙌🏼

**Comment by retraut** [comment]
Any news?

**Comment by matthewmodestino** [comment]
@rockb1017 can you review when you can?

**Comment by rockb1017** [comment]
will review this this week. sorry for late reply!

**Review by rockb1017 — APPROVED** [review]
Looks good. Thank you

**Pull request merged**
