### PR TITLE
Change default encoding to UTF-8 (in configMap.yaml)

### PR DESCRIPTION
**Pull request by BartekZm**
## Proposed changes

Change default ASCII-8BIT encoding to UTF-8
splunk-connect-for-kubernetes/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml:
add after line 75 
(https://github.com/splunk/splunk-connect-for-kubernetes/blob/79d17645af594762c9421cc184d59201a7ccb0a6/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L75):
encoding UTF-8
from_encoding UTF-8

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CONTRIBUTING.md) doc
- [x] I have read the [CLA](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CLA.md)
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by vinzent** [comment]
What issues do you have without this ? Can you share logs of errors?

**Comment by BartekZm** [comment]
#568 

See the issue:
https://github.com/splunk/splunk-connect-for-kubernetes/issues/568

**Comment by LennartHaggkvistHM** [comment]
To ensure backward compatibility you could add the below in the configMap.yaml file 
```
      {{- if .Values.fluentd.encoding.containers.encoding }}
      encoding {{ .Values.fluentd.encoding.containers.encoding }}
      {{- end }}
      {{- if .Values.fluentd.encoding.containers.fromEncoding }}
      from_encoding {{ .Values.fluentd.encoding.containers.fromEncoding }}
      {{- end }}
```

together with the values.yaml
```
splunk-kubernetes-logging:
  fluentd:
    encoding:
      containers:
        encoding: 
        fromEncoding: 
```

The default values mean that no configuration for envoding or from_encoding would be set, however, if one wants 
it we could override it, for example:
```
splunk-kubernetes-logging:
  fluentd:
    encoding:
      containers:
        encoding: UTF-8
        fromEncoding: UTF-8
```

(*note*: not sure about the best structure for the encoding configuration since it can probably can be more places where encoding  can be set. It would be more simpler if there were just one encoding value but I'm unsure about how it's used etc etc)

**Comment by vinzent** [comment]
+1 for @LennartHaggkvistHM idea of making it optional to not break anybodys logging.

But I think the change should be more like https://github.com/openshift/origin-aggregated-logging/pull/622 where the uft-8 conversion is done independently of the source type. actually they introduced it because not every source type supports setting the encoding.

**Comment by BartekZm** [comment]
Fixed in #570, closing as NTD

**Pull request closed without merging**
