### PR TITLE
Adds support for multiline customfilters, fixes #351

### LINKED ISSUE #351: Multiline customFilters YAML parse error
I've tried adding a multiline custom filter as follows:
```
splunk-kubernetes-logging:
  customFilters:
    RemovePasswords:
      tag: "**"
      type: grep
      body: |-
        <exclude>
          key $.object.message
          pattern /bindPassword|oc(\s)+login(\s)+(.*)--token/
        </exclude>
```

Then tried to install and got the following error:

> Error: UPGRADE FAILED: YAML parse error on splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml: error converting YAML to JSON: yaml: line 295: could not find expected ':'

This grep filter cannot be put onto a single line as fluentd gives the following error:
```
bundler: failed to load command: fluentd (/usr/bin/fluentd)
Fluent::ConfigParseError: expected end of line after tag at output.conf line 163,13
162:     @type grep
163:     <exclude> key $.object.message pattern /bindPassword|oc(\s)+login(\s)+(.*)--token/ </exclude>

     -------------^
164:   </filter>
```

So the fix is to change the configMap template to allow multiple lines.

### PR DESCRIPTION
**Pull request by fherbert**
## Proposed changes

Allow multiline customfilters for logging configmap.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CONTRIBUTING.md) doc
- [x] I have read the [CLA](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CLA.md)
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by rockb1017** [comment]
do you have example of multipline custom filter you would like to use?

**Comment by fherbert** [comment]
@rockb1017 sure, there's an example here https://github.com/splunk/splunk-connect-for-kubernetes/issues/351#issue-584052357

**Comment by rockb1017** [comment]
Thank you for contribution. 
it has to go through functional test pipeline, and only internal developers can trigger the pipeline. i have taken your changes in this PR https://github.com/splunk/splunk-connect-for-kubernetes/pull/369

**Comment by rockb1017** [comment]
Thank you. Merged

**Pull request closed without merging**
